#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai_Responses (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import hashlib
import os
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.frames.frames import Frame, TranscriptionFrame, TTSSpeakFrame
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor

from pipecat.runner.types import DailyRunnerArguments, RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.workers.runner import WorkerRunner

from pipecat.services.kokoro.tts import KokoroTTSService
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.whisper.stt import MLXModel, WhisperSTTServiceMLX
from pipecat.transports.local.audio import (
    LocalAudioTransport,
    LocalAudioTransportParams,
)

from langchain_text_splitters import RecursiveCharacterTextSplitter  
from langchain_ollama import OllamaEmbeddings
from pypdf import PdfReader
from langchain_core.documents import Document

import chromadb

from spoken_text_filter import SpokenTextFilter

load_dotenv(override=True)


class SimpleRAG:
    def __init__(self):
        self.db_path = "./rag_database"
        self.docs_path = "./docs"

        # Local Ollama
        self.embeddings = OllamaEmbeddings(model="nomic-embed-text")
        # self.llm = Ollama(model="qwen2.5:7b")

        # Local ChromaDB
        self.client = chromadb.PersistentClient(path=self.db_path)

    def _docs_fingerprint(self) -> str:
        """Hash of each PDF's path, size and mtime, so edits to ./docs force a rebuild."""
        h = hashlib.sha256()
        for pdf in sorted(Path(self.docs_path).glob("**/*.pdf")):
            stat = pdf.stat()
            h.update(f"{pdf}:{stat.st_size}:{stat.st_mtime_ns}".encode())
        return h.hexdigest()

    def build(self, force: bool = False):
        """Build database from PDFs, reusing the stored collection when it's current."""
        fingerprint = self._docs_fingerprint()
        collection = self.client.get_or_create_collection("docs")

        if not force and collection.count() > 0:
            if (collection.metadata or {}).get("fingerprint") == fingerprint:
                print(f"✅ Reusing existing database ({collection.count()} chunks)")
                return
            print("♻️  Documents changed since last build — rebuilding...")

        print("📂 Loading PDFs...")
        docs = []
        for pdf in sorted(Path(self.docs_path).glob("**/*.pdf")):
            for i, page in enumerate(PdfReader(pdf).pages):
                text = page.extract_text() or ""
                if text.strip():
                    docs.append(Document(page_content=text, metadata={"source": str(pdf), "page": i}))        

        if not docs:
            print(f"❌ No PDFs found in {self.docs_path}/")
            return

        print(f"✂️  Splitting {len(docs)} documents...")
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=50
        )
        chunks = splitter.split_documents(docs)

        # Drop and recreate rather than deleting ids, so a rebuild that produces
        # fewer chunks can't leave stale ones behind.
        self.client.delete_collection("docs")
        collection = self.client.create_collection(
            "docs", metadata={"fingerprint": fingerprint}
        )

        print(f"🧮 Creating embeddings for {len(chunks)} chunks...")
        batch_size = 64
        for start in range(0, len(chunks), batch_size):
            batch = chunks[start:start + batch_size]
            embeddings = self.embeddings.embed_documents([c.page_content for c in batch])
            collection.add(
                ids=[f"chunk_{start + i}" for i in range(len(batch))],
                documents=[c.page_content for c in batch],
                embeddings=embeddings,
                metadatas=[c.metadata or {} for c in batch]
            )
            print(f"  {min(start + batch_size, len(chunks))}/{len(chunks)}")

        print(f"✅ Database built! {len(chunks)} chunks ready")


    def make_context(self, question: str):
        collection = self.client.get_collection("docs")

        # Embed question
        q_embedding = self.embeddings.embed_documents([question])[0]

        # Retrieve relevant chunks
        results = collection.query(
            query_embeddings=[q_embedding],
            n_results=3
        )

        if not results['documents'][0]:
            return "No relevant information found."

        # Build context
        context = "\n\n".join(results['documents'][0])

        return context


class RagProcessor(FrameProcessor):
    """Retrieve passages for each user turn and refresh the system message."""

    def __init__(self, rag: SimpleRAG, context: LLMContext, base_prompt: str):
        super().__init__()
        self._rag = rag
        self._context = context
        self._base_prompt = base_prompt

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, TranscriptionFrame) and frame.text.strip():
            try:
                passages = await asyncio.to_thread(self._rag.make_context, frame.text)                                                                   
            except Exception as e:
                logger.warning(f"RAG retrieval failed, answering without it: {e}")
                passages = None

            if passages:
                system = (
                    f"{self._base_prompt}\n\n"
                    "Answer using only the reference material below. If it does "
                    "not cover the question, say so rather than guessing.\n\n"
                    f"--- Reference material ---\n{passages}"
                )
                self._context.transform_messages(
                    lambda msgs: [{"role": "system", "content": system}]                                                                                 
                    + [m for m in msgs if not (isinstance(m, dict) and m.get("role") == "system")]
                )

        await self.push_frame(frame, direction)

async def _speak_greeting(worker: PipelineWorker) -> None:
    """Speak a short opening line shortly after the pipeline starts.

    `LocalAudioTransport` does NOT emit an `on_client_connected` event — that
    event only fires on networked transports (WebSocket/WebRTC/Daily/etc.), so
    hooking it here would silently never run. Instead, mirroring Pipecat's own
    `getting-started/01a-local-audio.py`, we wait briefly for the audio output
    stream to come up, then queue a `TTSSpeakFrame`.
    """
    await asyncio.sleep(1)
    await worker.queue_frames([TTSSpeakFrame("hello! ask me about bees")])


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    rag = SimpleRAG()
    rag.build()

    # Speech-to-Text service
    stt_model = MLXModel["LARGE_V3_TURBO"]
    stt = WhisperSTTServiceMLX(settings=WhisperSTTServiceMLX.Settings(model=stt_model))

    # Text-to-Speech service
    MODEL_DIR = Path(os.environ.get("LLLLM_PIPECAT_MODEL_DIR", "./models"))
    model_path = MODEL_DIR / "kokoro" / "kokoro-v1.0.onnx"
    voices_path = MODEL_DIR / "kokoro" / "voices-v1.0.bin"
    tts = KokoroTTSService(
        settings=KokoroTTSService.Settings(voice="af_heart"),
        model_path=model_path,
        voices_path=voices_path,
        text_filters=[SpokenTextFilter()],
    )

    # LLM service
    llm_model="qwen2.5:14b"
    # llm_model="deepseek-r1:14b"
    llm = OLLamaLLMService(
        settings=OLLamaLLMService.Settings(model=llm_model),
        base_url="http://localhost:11434/v1",
    )
 
    SYSTEM_PROMPT= "you are a helpful assistant who knows a lot about bees and bee husbandry"
    context = LLMContext(messages=[{"role": "system", "content": SYSTEM_PROMPT}])
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    rag_processor = RagProcessor(rag, context, SYSTEM_PROMPT)

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            rag_processor,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message(
            {"role": "developer", "content": "Start by concisely introducing yourself."}
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)

    # await runner.run()
    await asyncio.gather(runner.run(), _speak_greeting(worker))




async def main():
    """Main bot entry point."""

    input_raw = os.getenv("INPUT_DEVICE_INDEX", "").strip()
    output_raw = os.getenv("OUTPUT_DEVICE_INDEX", "").strip()

    params = LocalAudioTransportParams(
        audio_in_enabled=True,
        audio_out_enabled=True,
        input_device_index=int(input_raw) if input_raw else None,
        output_device_index=int(output_raw) if output_raw else None,
    )

    transport = LocalAudioTransport(params)

    await run_bot(transport)


if __name__ == "__main__":
    asyncio.run(main())
